// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: spotify_api_v2

#ifndef UI_ALBUMSCREEN_H
#define UI_ALBUMSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_albumScreen
extern void ui_albumScreen_screen_init(void);
extern void ui_albumScreen_screen_destroy(void);
extern lv_obj_t * ui_albumScreen;
extern lv_obj_t * ui_menupanel;
extern lv_obj_t * ui_playingPanel;
extern lv_obj_t * ui_playingsButton;
extern lv_obj_t * ui_playingImage;
extern lv_obj_t * ui_playingLabel;
extern lv_obj_t * ui_homePanel;
extern lv_obj_t * ui_homeButton;
extern lv_obj_t * ui_homeImage;
extern lv_obj_t * ui_homeLabel;
extern lv_obj_t * ui_libraryPanel;
extern lv_obj_t * ui_libraryButton;
extern lv_obj_t * ui_libraryImage;
extern lv_obj_t * ui_libraryLabel;
extern lv_obj_t * ui_albumsPanel;
extern lv_obj_t * ui_albumsButton;
extern lv_obj_t * ui_albumsImage;
extern lv_obj_t * ui_albumsLabel;
extern lv_obj_t * ui_artistsPanel;
extern lv_obj_t * ui_artistsButton;
extern lv_obj_t * ui_artistsImage;
extern lv_obj_t * ui_artistsLabel;
extern lv_obj_t * ui_playlistsPanel;
extern lv_obj_t * ui_playlistsButton;
extern lv_obj_t * ui_playlistsImage;
extern lv_obj_t * ui_playlistsLabel;
extern lv_obj_t * ui_settingsPanel;
extern lv_obj_t * ui_settingsButton;
extern lv_obj_t * ui_settingsImage;
extern lv_obj_t * ui_settingsLabel;
extern lv_obj_t * ui_colPanel;
extern lv_obj_t * ui_albumPanel;
extern lv_obj_t * ui_albumImage;
extern lv_obj_t * ui_albumLabel;
extern lv_obj_t * ui_albumArtistLabel;
extern lv_obj_t * ui_pausePlayButton2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

