// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: spotify_api_v2

#include "ui.h"

lv_obj_t * ui_albumScreen;
lv_obj_t * ui_menupanel;
lv_obj_t * ui_playingPanel;
lv_obj_t * ui_playingsButton;
lv_obj_t * ui_playingImage;
lv_obj_t * ui_playingLabel;
lv_obj_t * ui_homePanel;
lv_obj_t * ui_homeButton;
lv_obj_t * ui_homeImage;
lv_obj_t * ui_homeLabel;
lv_obj_t * ui_libraryPanel;
lv_obj_t * ui_libraryButton;
lv_obj_t * ui_libraryImage;
lv_obj_t * ui_libraryLabel;
lv_obj_t * ui_albumsPanel;
lv_obj_t * ui_albumsButton;
lv_obj_t * ui_albumsImage;
lv_obj_t * ui_albumsLabel;
lv_obj_t * ui_artistsPanel;
lv_obj_t * ui_artistsButton;
lv_obj_t * ui_artistsImage;
lv_obj_t * ui_artistsLabel;
lv_obj_t * ui_playlistsPanel;
lv_obj_t * ui_playlistsButton;
lv_obj_t * ui_playlistsImage;
lv_obj_t * ui_playlistsLabel;
lv_obj_t * ui_settingsPanel;
lv_obj_t * ui_settingsButton;
lv_obj_t * ui_settingsImage;
lv_obj_t * ui_settingsLabel;
lv_obj_t * ui_colPanel;
lv_obj_t * ui_albumPanel;
lv_obj_t * ui_albumImage;
lv_obj_t * ui_albumLabel;
lv_obj_t * ui_albumArtistLabel;
lv_obj_t * ui_pausePlayButton2;

// event funtions

// build funtions

void ui_albumScreen_screen_init(void)
{
    ui_albumScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_albumScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_albumScreen, &ui_img_1559207837, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_albumScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_albumScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menupanel = lv_obj_create(ui_albumScreen);
    lv_obj_set_width(ui_menupanel, 240);
    lv_obj_set_height(ui_menupanel, 480);
    lv_obj_set_align(ui_menupanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_menupanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_menupanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_menupanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_menupanel, LV_DIR_VER);
    lv_obj_set_style_radius(ui_menupanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menupanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menupanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_menupanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_menupanel, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_menupanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_menupanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_menupanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_menupanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_menupanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playingPanel = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_playingPanel, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_playingPanel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_playingPanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_playingPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_playingPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_playingPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_playingPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_playingPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_playingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_playingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_playingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_playingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playingsButton = lv_button_create(ui_playingPanel);
    lv_obj_set_width(ui_playingsButton, 70);
    lv_obj_set_height(ui_playingsButton, 70);
    lv_obj_set_align(ui_playingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_playingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_playingsButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_playingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playingsButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playingImage = lv_image_create(ui_playingsButton);
    lv_image_set_src(ui_playingImage, &ui_img_playing_png);
    lv_obj_set_width(ui_playingImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playingImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_playingImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playingImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_playingImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_playingLabel = lv_label_create(ui_playingPanel);
    lv_obj_set_width(ui_playingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_playingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_playingLabel, "Playing");
    lv_obj_set_style_text_letter_space(ui_playingLabel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_playingLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_playingLabel, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homePanel = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_homePanel, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_homePanel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_homePanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_homePanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_homePanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_homePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_homePanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_homePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeButton = lv_button_create(ui_homePanel);
    lv_obj_set_width(ui_homeButton, 70);
    lv_obj_set_height(ui_homeButton, 70);
    lv_obj_set_align(ui_homeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_homeButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homeButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeImage = lv_image_create(ui_homeButton);
    lv_image_set_src(ui_homeImage, &ui_img_home_png);
    lv_obj_set_width(ui_homeImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homeImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_homeImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_homeImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homeLabel = lv_label_create(ui_homePanel);
    lv_obj_set_width(ui_homeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_homeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_homeLabel, "Home");
    lv_obj_set_style_text_letter_space(ui_homeLabel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_homeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_homeLabel, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_libraryPanel = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_libraryPanel, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_libraryPanel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_libraryPanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_libraryPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_libraryPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_libraryPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_libraryPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_libraryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_libraryPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_libraryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_libraryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_libraryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_libraryPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_libraryButton = lv_button_create(ui_libraryPanel);
    lv_obj_set_width(ui_libraryButton, 70);
    lv_obj_set_height(ui_libraryButton, 70);
    lv_obj_set_align(ui_libraryButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_libraryButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_libraryButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_libraryButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_libraryButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_libraryButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_libraryImage = lv_image_create(ui_libraryButton);
    lv_image_set_src(ui_libraryImage, &ui_img_library_png);
    lv_obj_set_width(ui_libraryImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_libraryImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_libraryImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_libraryImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_libraryImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_libraryLabel = lv_label_create(ui_libraryPanel);
    lv_obj_set_width(ui_libraryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_libraryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_libraryLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_libraryLabel, "Library");
    lv_obj_set_style_text_letter_space(ui_libraryLabel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_libraryLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_libraryLabel, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumsPanel = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_albumsPanel, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_albumsPanel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_albumsPanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_albumsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_albumsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_albumsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_albumsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_albumsPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_albumsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_albumsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_albumsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_albumsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumsButton = lv_button_create(ui_albumsPanel);
    lv_obj_set_width(ui_albumsButton, 70);
    lv_obj_set_height(ui_albumsButton, 70);
    lv_obj_set_align(ui_albumsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_albumsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_albumsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_albumsButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_albumsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumsButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumsImage = lv_image_create(ui_albumsButton);
    lv_image_set_src(ui_albumsImage, &ui_img_albums_png);
    lv_obj_set_width(ui_albumsImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_albumsImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_albumsImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_albumsImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_albumsImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_albumsLabel = lv_label_create(ui_albumsPanel);
    lv_obj_set_width(ui_albumsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_albumsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_albumsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_albumsLabel, "Albums");
    lv_obj_set_style_text_letter_space(ui_albumsLabel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_albumsLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_albumsLabel, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_artistsPanel = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_artistsPanel, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_artistsPanel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_artistsPanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_artistsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_artistsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_artistsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_artistsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_artistsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_artistsPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_artistsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_artistsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_artistsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_artistsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_artistsButton = lv_button_create(ui_artistsPanel);
    lv_obj_set_width(ui_artistsButton, 70);
    lv_obj_set_height(ui_artistsButton, 70);
    lv_obj_set_align(ui_artistsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_artistsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_artistsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_artistsButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_artistsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_artistsButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_artistsImage = lv_image_create(ui_artistsButton);
    lv_image_set_src(ui_artistsImage, &ui_img_artist_png);
    lv_obj_set_width(ui_artistsImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_artistsImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_artistsImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_artistsImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_artistsImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_artistsLabel = lv_label_create(ui_artistsPanel);
    lv_obj_set_width(ui_artistsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_artistsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_artistsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_artistsLabel, "Artists");
    lv_obj_set_style_text_letter_space(ui_artistsLabel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_artistsLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_artistsLabel, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playlistsPanel = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_playlistsPanel, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_playlistsPanel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_playlistsPanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_playlistsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_playlistsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_playlistsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_playlistsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playlistsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_playlistsPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_playlistsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_playlistsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_playlistsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_playlistsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playlistsButton = lv_button_create(ui_playlistsPanel);
    lv_obj_set_width(ui_playlistsButton, 70);
    lv_obj_set_height(ui_playlistsButton, 70);
    lv_obj_set_align(ui_playlistsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playlistsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_playlistsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_playlistsButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_playlistsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playlistsButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playlistsImage = lv_image_create(ui_playlistsButton);
    lv_image_set_src(ui_playlistsImage, &ui_img_playlist_png);
    lv_obj_set_width(ui_playlistsImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playlistsImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_playlistsImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playlistsImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_playlistsImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_playlistsLabel = lv_label_create(ui_playlistsPanel);
    lv_obj_set_width(ui_playlistsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playlistsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_playlistsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_playlistsLabel, "Playlists");
    lv_obj_set_style_text_letter_space(ui_playlistsLabel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_playlistsLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_playlistsLabel, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsPanel = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_settingsPanel, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_settingsPanel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_settingsPanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_settingsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_settingsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settingsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_settingsPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_settingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_settingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_settingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_settingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsButton = lv_button_create(ui_settingsPanel);
    lv_obj_set_width(ui_settingsButton, 70);
    lv_obj_set_height(ui_settingsButton, 70);
    lv_obj_set_align(ui_settingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_settingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_settingsButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsImage = lv_image_create(ui_settingsButton);
    lv_image_set_src(ui_settingsImage, &ui_img_settings_png);
    lv_obj_set_width(ui_settingsImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settingsImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settingsImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingsLabel = lv_label_create(ui_settingsPanel);
    lv_obj_set_width(ui_settingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settingsLabel, "Settings");
    lv_obj_set_style_text_letter_space(ui_settingsLabel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_settingsLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settingsLabel, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_colPanel = lv_obj_create(ui_albumScreen);
    lv_obj_set_width(ui_colPanel, 560);
    lv_obj_set_height(ui_colPanel, 480);
    lv_obj_set_x(ui_colPanel, 240);
    lv_obj_set_y(ui_colPanel, 0);
    lv_obj_set_align(ui_colPanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_colPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_colPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_colPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_colPanel, LV_DIR_VER);
    lv_obj_set_scroll_snap_y(ui_colPanel, LV_SCROLL_SNAP_START);
    lv_obj_set_style_radius(ui_colPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_colPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_colPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_colPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_colPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_colPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_colPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_colPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_colPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_colPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumPanel = lv_obj_create(ui_colPanel);
    lv_obj_set_width(ui_albumPanel, 170);
    lv_obj_set_height(ui_albumPanel, 160);
    lv_obj_set_align(ui_albumPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_albumPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_albumPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_albumPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_albumPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_albumPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_albumPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumImage = lv_image_create(ui_albumPanel);
    lv_obj_set_width(ui_albumImage, 64);
    lv_obj_set_height(ui_albumImage, 64);
    lv_obj_set_x(ui_albumImage, 0);
    lv_obj_set_y(ui_albumImage, -28);
    lv_obj_set_align(ui_albumImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_albumImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_albumImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_albumLabel = lv_label_create(ui_albumPanel);
    lv_obj_set_width(ui_albumLabel, 160);
    lv_obj_set_height(ui_albumLabel, 30);
    lv_obj_set_x(ui_albumLabel, 0);
    lv_obj_set_y(ui_albumLabel, 27);
    lv_obj_set_align(ui_albumLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_albumLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_albumLabel, "Album Title");
    lv_obj_set_style_text_letter_space(ui_albumLabel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_albumLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_albumLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_albumLabel, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumArtistLabel = lv_label_create(ui_albumPanel);
    lv_obj_set_width(ui_albumArtistLabel, 160);
    lv_obj_set_height(ui_albumArtistLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_albumArtistLabel, 0);
    lv_obj_set_y(ui_albumArtistLabel, 52);
    lv_obj_set_align(ui_albumArtistLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_albumArtistLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_albumArtistLabel, "Artist Name");
    lv_obj_set_style_text_align(ui_albumArtistLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_albumArtistLabel, &ui_font_inter162, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pausePlayButton2 = lv_button_create(ui_albumScreen);
    lv_obj_set_width(ui_pausePlayButton2, 100);
    lv_obj_set_height(ui_pausePlayButton2, 100);
    lv_obj_set_x(ui_pausePlayButton2, -20);
    lv_obj_set_y(ui_pausePlayButton2, -20);
    lv_obj_set_align(ui_pausePlayButton2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_pausePlayButton2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_pausePlayButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pausePlayButton2, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pausePlayButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pausePlayButton2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pausePlayButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_pausePlayButton2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

}

void ui_albumScreen_screen_destroy(void)
{
    if(ui_albumScreen) lv_obj_del(ui_albumScreen);

    // NULL screen variables
    ui_albumScreen = NULL;
    ui_menupanel = NULL;
    ui_playingPanel = NULL;
    ui_playingsButton = NULL;
    ui_playingImage = NULL;
    ui_playingLabel = NULL;
    ui_homePanel = NULL;
    ui_homeButton = NULL;
    ui_homeImage = NULL;
    ui_homeLabel = NULL;
    ui_libraryPanel = NULL;
    ui_libraryButton = NULL;
    ui_libraryImage = NULL;
    ui_libraryLabel = NULL;
    ui_albumsPanel = NULL;
    ui_albumsButton = NULL;
    ui_albumsImage = NULL;
    ui_albumsLabel = NULL;
    ui_artistsPanel = NULL;
    ui_artistsButton = NULL;
    ui_artistsImage = NULL;
    ui_artistsLabel = NULL;
    ui_playlistsPanel = NULL;
    ui_playlistsButton = NULL;
    ui_playlistsImage = NULL;
    ui_playlistsLabel = NULL;
    ui_settingsPanel = NULL;
    ui_settingsButton = NULL;
    ui_settingsImage = NULL;
    ui_settingsLabel = NULL;
    ui_colPanel = NULL;
    ui_albumPanel = NULL;
    ui_albumImage = NULL;
    ui_albumLabel = NULL;
    ui_albumArtistLabel = NULL;
    ui_pausePlayButton2 = NULL;

}
