// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: spotify_api_v2

#include "ui.h"

void handle_now_playing(lv_event_t * e)
{
	// Your code here
}
