// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: spotify_api_v2

#ifndef UI_SONGSCREEN_H
#define UI_SONGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_songScreen
extern void ui_songScreen_screen_init(void);
extern void ui_songScreen_screen_destroy(void);
extern lv_obj_t * ui_songScreen;
extern lv_obj_t * ui_menupanel1;
extern lv_obj_t * ui_playingPanel1;
extern lv_obj_t * ui_playingsButton1;
extern lv_obj_t * ui_playingImage1;
extern lv_obj_t * ui_playingLabel1;
extern lv_obj_t * ui_homePanel1;
extern lv_obj_t * ui_homeButton1;
extern lv_obj_t * ui_homeImage1;
extern lv_obj_t * ui_homeLabel1;
extern lv_obj_t * ui_libraryPanel1;
extern lv_obj_t * ui_libraryButton1;
extern lv_obj_t * ui_libraryImage1;
extern lv_obj_t * ui_libraryLabel1;
extern lv_obj_t * ui_albumsPanel1;
extern lv_obj_t * ui_albumsButton1;
extern lv_obj_t * ui_albumsImage1;
extern lv_obj_t * ui_albumsLabel1;
extern lv_obj_t * ui_artistsPanel1;
extern lv_obj_t * ui_artistsButton1;
extern lv_obj_t * ui_artistsImage1;
extern lv_obj_t * ui_artistsLabel1;
extern lv_obj_t * ui_playlistsPanel1;
extern lv_obj_t * ui_playlistsButton1;
extern lv_obj_t * ui_playlistsImage1;
extern lv_obj_t * ui_playlistsLabel1;
extern lv_obj_t * ui_settingsPanel1;
extern lv_obj_t * ui_settingsButton1;
extern lv_obj_t * ui_settingsImage1;
extern lv_obj_t * ui_settingsLabel1;
extern lv_obj_t * ui_rowPanel;
extern lv_obj_t * ui_songPanel;
extern lv_obj_t * ui_songImage;
extern lv_obj_t * ui_songTitle;
extern lv_obj_t * ui_contextLabel;
extern lv_obj_t * ui_lengthLabel;
extern lv_obj_t * ui_pausePlayButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

