// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: spotify_api_v2

#include "ui.h"

lv_obj_t *ui_Screen1;
lv_obj_t *ui_menupanel;
lv_obj_t *ui_nowPlayingPanel;
lv_obj_t *ui_nowPlayingButton;
lv_obj_t *ui_Image2;
lv_obj_t *ui_nowPlayingLabel;
lv_obj_t *ui_nowPlayingPanel1;
lv_obj_t *ui_nowPlayingButton1;
lv_obj_t *ui_Image1;
lv_obj_t *ui_nowPlayingLabel1;
lv_obj_t *ui_nowPlayingPanel2;
lv_obj_t *ui_nowPlayingButton2;
lv_obj_t *ui_Image3;
lv_obj_t *ui_nowPlayingLabel2;
lv_obj_t *ui_nowPlayingPanel3;
lv_obj_t *ui_nowPlayingButton3;
lv_obj_t *ui_Image4;
lv_obj_t *ui_nowPlayingLabel3;
lv_obj_t *ui_nowPlayingPanel4;
lv_obj_t *ui_nowPlayingButton4;
lv_obj_t *ui_Image5;
lv_obj_t *ui_nowPlayingLabel4;
lv_obj_t *ui_nowPlayingPanel5;
lv_obj_t *ui_nowPlayingButton5;
lv_obj_t *ui_Image6;
lv_obj_t *ui_nowPlayingLabel5;
lv_obj_t *ui_contentpanel;
lv_obj_t *ui_contentItemPanel;
lv_obj_t *ui_albumCoverButton;
lv_obj_t *ui_contentTitle;
lv_obj_t *ui_creatorLabel;
lv_obj_t *ui_contentItemPanel10;
lv_obj_t *ui_albumCoverButton10;
lv_obj_t *ui_contentTitle10;
static lv_style_t style_rounded_corners;

// event funtions
void ui_event_nowPlayingButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        handle_now_playing(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_flex_flow(ui_Screen1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_1559207837, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_style_init(&style_rounded_corners);
    lv_style_set_radius(&style_rounded_corners, 20); // Or any specific radius, e.g., 20
    lv_style_set_clip_corner(&style_rounded_corners, true);

    ui_menupanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_menupanel, 290);
    lv_obj_set_height(ui_menupanel, 480);
    lv_obj_set_x(ui_menupanel, 37);
    lv_obj_set_y(ui_menupanel, -342);
    lv_obj_set_align(ui_menupanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_menupanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_menupanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_menupanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_menupanel, LV_DIR_VER);
    lv_obj_set_style_radius(ui_menupanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menupanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menupanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_menupanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_menupanel, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_menupanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_menupanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_menupanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_menupanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_menupanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingPanel = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_nowPlayingPanel, LV_SIZE_CONTENT);  /// 270
    lv_obj_set_height(ui_nowPlayingPanel, LV_SIZE_CONTENT); /// 100
    lv_obj_set_align(ui_nowPlayingPanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_nowPlayingPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_nowPlayingPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nowPlayingPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_nowPlayingPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_nowPlayingPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_nowPlayingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_nowPlayingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_nowPlayingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_nowPlayingPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingButton = lv_button_create(ui_nowPlayingPanel);
    lv_obj_set_width(ui_nowPlayingButton, 70);
    lv_obj_set_height(ui_nowPlayingButton, 70);
    lv_obj_set_align(ui_nowPlayingButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nowPlayingButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_nowPlayingButton, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_nowPlayingButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nowPlayingButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_nowPlayingButton);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);                    /// Flags

    ui_nowPlayingLabel = lv_label_create(ui_nowPlayingPanel);
    lv_obj_set_width(ui_nowPlayingLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_nowPlayingLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_nowPlayingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nowPlayingLabel, "Now Playing");
    lv_obj_set_style_text_letter_space(ui_nowPlayingLabel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_nowPlayingLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nowPlayingLabel, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingPanel1 = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_nowPlayingPanel1, LV_SIZE_CONTENT);  /// 270
    lv_obj_set_height(ui_nowPlayingPanel1, LV_SIZE_CONTENT); /// 100
    lv_obj_set_align(ui_nowPlayingPanel1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_nowPlayingPanel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_nowPlayingPanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nowPlayingPanel1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_nowPlayingPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_nowPlayingPanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_nowPlayingPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_nowPlayingPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_nowPlayingPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_nowPlayingPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingButton1 = lv_button_create(ui_nowPlayingPanel1);
    lv_obj_set_width(ui_nowPlayingButton1, 70);
    lv_obj_set_height(ui_nowPlayingButton1, 70);
    lv_obj_set_align(ui_nowPlayingButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nowPlayingButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_nowPlayingButton1, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_nowPlayingButton1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nowPlayingButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingButton1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_nowPlayingButton1);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);                    /// Flags

    ui_nowPlayingLabel1 = lv_label_create(ui_nowPlayingPanel1);
    lv_obj_set_width(ui_nowPlayingLabel1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_nowPlayingLabel1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_nowPlayingLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nowPlayingLabel1, "Recents");
    lv_obj_set_style_text_letter_space(ui_nowPlayingLabel1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_nowPlayingLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nowPlayingLabel1, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingPanel2 = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_nowPlayingPanel2, LV_SIZE_CONTENT);  /// 270
    lv_obj_set_height(ui_nowPlayingPanel2, LV_SIZE_CONTENT); /// 100
    lv_obj_set_align(ui_nowPlayingPanel2, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_nowPlayingPanel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_nowPlayingPanel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nowPlayingPanel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_nowPlayingPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_nowPlayingPanel2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_nowPlayingPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_nowPlayingPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_nowPlayingPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_nowPlayingPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingButton2 = lv_button_create(ui_nowPlayingPanel2);
    lv_obj_set_width(ui_nowPlayingButton2, 70);
    lv_obj_set_height(ui_nowPlayingButton2, 70);
    lv_obj_set_align(ui_nowPlayingButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nowPlayingButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_nowPlayingButton2, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_nowPlayingButton2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nowPlayingButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingButton2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_nowPlayingButton2);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);                    /// Flags

    ui_nowPlayingLabel2 = lv_label_create(ui_nowPlayingPanel2);
    lv_obj_set_width(ui_nowPlayingLabel2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_nowPlayingLabel2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_nowPlayingLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nowPlayingLabel2, "Library");
    lv_obj_set_style_text_letter_space(ui_nowPlayingLabel2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_nowPlayingLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nowPlayingLabel2, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingPanel3 = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_nowPlayingPanel3, LV_SIZE_CONTENT);  /// 270
    lv_obj_set_height(ui_nowPlayingPanel3, LV_SIZE_CONTENT); /// 100
    lv_obj_set_align(ui_nowPlayingPanel3, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_nowPlayingPanel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_nowPlayingPanel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nowPlayingPanel3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_nowPlayingPanel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_nowPlayingPanel3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_nowPlayingPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_nowPlayingPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_nowPlayingPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_nowPlayingPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingButton3 = lv_button_create(ui_nowPlayingPanel3);
    lv_obj_set_width(ui_nowPlayingButton3, 70);
    lv_obj_set_height(ui_nowPlayingButton3, 70);
    lv_obj_set_align(ui_nowPlayingButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nowPlayingButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_nowPlayingButton3, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_nowPlayingButton3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nowPlayingButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingButton3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_nowPlayingButton3);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);                    /// Flags

    ui_nowPlayingLabel3 = lv_label_create(ui_nowPlayingPanel3);
    lv_obj_set_width(ui_nowPlayingLabel3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_nowPlayingLabel3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_nowPlayingLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nowPlayingLabel3, "Artists");
    lv_obj_set_style_text_letter_space(ui_nowPlayingLabel3, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_nowPlayingLabel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nowPlayingLabel3, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingPanel4 = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_nowPlayingPanel4, LV_SIZE_CONTENT);  /// 270
    lv_obj_set_height(ui_nowPlayingPanel4, LV_SIZE_CONTENT); /// 100
    lv_obj_set_align(ui_nowPlayingPanel4, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_nowPlayingPanel4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_nowPlayingPanel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nowPlayingPanel4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_nowPlayingPanel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_nowPlayingPanel4, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_nowPlayingPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_nowPlayingPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_nowPlayingPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_nowPlayingPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingButton4 = lv_button_create(ui_nowPlayingPanel4);
    lv_obj_set_width(ui_nowPlayingButton4, 70);
    lv_obj_set_height(ui_nowPlayingButton4, 70);
    lv_obj_set_align(ui_nowPlayingButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nowPlayingButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_nowPlayingButton4, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_nowPlayingButton4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nowPlayingButton4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingButton4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_nowPlayingButton4);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);                    /// Flags

    ui_nowPlayingLabel4 = lv_label_create(ui_nowPlayingPanel4);
    lv_obj_set_width(ui_nowPlayingLabel4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_nowPlayingLabel4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_nowPlayingLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nowPlayingLabel4, "Radio");
    lv_obj_set_style_text_letter_space(ui_nowPlayingLabel4, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_nowPlayingLabel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nowPlayingLabel4, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingPanel5 = lv_obj_create(ui_menupanel);
    lv_obj_set_width(ui_nowPlayingPanel5, LV_SIZE_CONTENT);  /// 270
    lv_obj_set_height(ui_nowPlayingPanel5, LV_SIZE_CONTENT); /// 100
    lv_obj_set_align(ui_nowPlayingPanel5, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_nowPlayingPanel5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_nowPlayingPanel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nowPlayingPanel5, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_nowPlayingPanel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingPanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_nowPlayingPanel5, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_nowPlayingPanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_nowPlayingPanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_nowPlayingPanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_nowPlayingPanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nowPlayingButton5 = lv_button_create(ui_nowPlayingPanel5);
    lv_obj_set_width(ui_nowPlayingButton5, 70);
    lv_obj_set_height(ui_nowPlayingButton5, 70);
    lv_obj_set_align(ui_nowPlayingButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nowPlayingButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_nowPlayingButton5, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_radius(ui_nowPlayingButton5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nowPlayingButton5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nowPlayingButton5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_image_create(ui_nowPlayingButton5);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);                    /// Flags

    ui_nowPlayingLabel5 = lv_label_create(ui_nowPlayingPanel5);
    lv_obj_set_width(ui_nowPlayingLabel5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_nowPlayingLabel5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_nowPlayingLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nowPlayingLabel5, "Settings");
    lv_obj_set_style_text_letter_space(ui_nowPlayingLabel5, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_nowPlayingLabel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nowPlayingLabel5, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contentpanel = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_contentpanel, 480);
    lv_obj_set_flex_grow(ui_contentpanel, 1);
    lv_obj_set_x(ui_contentpanel, 152);
    lv_obj_set_y(ui_contentpanel, -2);
    lv_obj_set_align(ui_contentpanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contentpanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contentpanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_contentpanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_contentpanel, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_contentpanel, LV_SCROLL_SNAP_START);
    lv_obj_set_style_radius(ui_contentpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contentpanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contentpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_contentpanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contentpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contentpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contentpanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contentpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contentpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contentpanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contentItemPanel = lv_obj_create(ui_contentpanel);
    lv_obj_set_width(ui_contentItemPanel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_contentItemPanel, LV_SIZE_CONTENT); /// 50
    lv_obj_set_x(ui_contentItemPanel, 0);
    lv_obj_set_y(ui_contentItemPanel, 1);
    lv_obj_set_align(ui_contentItemPanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_contentItemPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contentItemPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_contentItemPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_contentItemPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contentItemPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_contentItemPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contentItemPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contentItemPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contentItemPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contentItemPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contentItemPanel, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contentItemPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumCoverButton = lv_imgbtn_create(ui_contentItemPanel);
    lv_obj_set_width(ui_albumCoverButton, 64);
    lv_obj_set_height(ui_albumCoverButton, 64);
    lv_obj_set_align(ui_albumCoverButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_albumCoverButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_albumCoverButton, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_imagebutton_set_src(ui_albumCoverButton, LV_IMGBTN_STATE_RELEASED, "S:test.jpg", NULL, NULL);
    lv_obj_add_style(ui_albumCoverButton, &style_rounded_corners, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contentTitle = lv_label_create(ui_contentItemPanel);
    lv_obj_set_width(ui_contentTitle, 300);
    lv_obj_set_height(ui_contentTitle, 36);
    lv_obj_set_align(ui_contentTitle, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_contentTitle, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_contentTitle, "Long title that runs off the screen");
    lv_obj_set_style_text_letter_space(ui_contentTitle, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_contentTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_contentTitle, &ui_font_Inter30Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_creatorLabel = lv_label_create(ui_contentItemPanel);
    lv_obj_set_width(ui_creatorLabel, 300);
    lv_obj_set_height(ui_creatorLabel, 36);
    lv_obj_set_x(ui_creatorLabel, -2);
    lv_obj_set_y(ui_creatorLabel, 0);
    lv_obj_set_align(ui_creatorLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_creatorLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_creatorLabel, "Long artist name that runs off ");
    lv_obj_set_style_text_letter_space(ui_creatorLabel, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_creatorLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_creatorLabel, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contentItemPanel10 = lv_obj_create(ui_contentpanel);
    lv_obj_set_width(ui_contentItemPanel10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_contentItemPanel10, LV_SIZE_CONTENT); /// 50
    lv_obj_set_x(ui_contentItemPanel10, 0);
    lv_obj_set_y(ui_contentItemPanel10, 1);
    lv_obj_set_align(ui_contentItemPanel10, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_contentItemPanel10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contentItemPanel10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_contentItemPanel10, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_contentItemPanel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contentItemPanel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_contentItemPanel10, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contentItemPanel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contentItemPanel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contentItemPanel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contentItemPanel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contentItemPanel10, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contentItemPanel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumCoverButton10 = lv_button_create(ui_contentItemPanel10);
    lv_obj_set_width(ui_albumCoverButton10, 100);
    lv_obj_set_height(ui_albumCoverButton10, 300);
    lv_obj_set_align(ui_albumCoverButton10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_albumCoverButton10, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_remove_flag(ui_albumCoverButton10, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
    lv_obj_set_style_bg_color(ui_albumCoverButton10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumCoverButton10, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contentTitle10 = lv_label_create(ui_contentItemPanel10);
    lv_obj_set_width(ui_contentTitle10, 100);
    lv_obj_set_height(ui_contentTitle10, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_contentTitle10, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_contentTitle10, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_contentTitle10, "Load More");
    lv_obj_set_style_text_letter_space(ui_contentTitle10, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_contentTitle10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_contentTitle10, &ui_font_Inter30Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_nowPlayingButton, ui_event_nowPlayingButton, LV_EVENT_ALL, NULL);
}

void ui_Screen1_screen_destroy(void)
{
    if (ui_Screen1)
        lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_menupanel = NULL;
    ui_nowPlayingPanel = NULL;
    ui_nowPlayingButton = NULL;
    ui_Image2 = NULL;
    ui_nowPlayingLabel = NULL;
    ui_nowPlayingPanel1 = NULL;
    ui_nowPlayingButton1 = NULL;
    ui_Image1 = NULL;
    ui_nowPlayingLabel1 = NULL;
    ui_nowPlayingPanel2 = NULL;
    ui_nowPlayingButton2 = NULL;
    ui_Image3 = NULL;
    ui_nowPlayingLabel2 = NULL;
    ui_nowPlayingPanel3 = NULL;
    ui_nowPlayingButton3 = NULL;
    ui_Image4 = NULL;
    ui_nowPlayingLabel3 = NULL;
    ui_nowPlayingPanel4 = NULL;
    ui_nowPlayingButton4 = NULL;
    ui_Image5 = NULL;
    ui_nowPlayingLabel4 = NULL;
    ui_nowPlayingPanel5 = NULL;
    ui_nowPlayingButton5 = NULL;
    ui_Image6 = NULL;
    ui_nowPlayingLabel5 = NULL;
    ui_contentpanel = NULL;
    ui_contentItemPanel = NULL;
    ui_albumCoverButton = NULL;
    ui_contentTitle = NULL;
    ui_creatorLabel = NULL;
    ui_contentItemPanel10 = NULL;
    ui_albumCoverButton10 = NULL;
    ui_contentTitle10 = NULL;
}
