// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: spotify_api_v2

#include "ui.h"

lv_obj_t * ui_songScreen;
lv_obj_t * ui_menupanel1;
lv_obj_t * ui_playingPanel1;
lv_obj_t * ui_playingsButton1;
lv_obj_t * ui_playingImage1;
lv_obj_t * ui_playingLabel1;
lv_obj_t * ui_homePanel1;
lv_obj_t * ui_homeButton1;
lv_obj_t * ui_homeImage1;
lv_obj_t * ui_homeLabel1;
lv_obj_t * ui_libraryPanel1;
lv_obj_t * ui_libraryButton1;
lv_obj_t * ui_libraryImage1;
lv_obj_t * ui_libraryLabel1;
lv_obj_t * ui_albumsPanel1;
lv_obj_t * ui_albumsButton1;
lv_obj_t * ui_albumsImage1;
lv_obj_t * ui_albumsLabel1;
lv_obj_t * ui_artistsPanel1;
lv_obj_t * ui_artistsButton1;
lv_obj_t * ui_artistsImage1;
lv_obj_t * ui_artistsLabel1;
lv_obj_t * ui_playlistsPanel1;
lv_obj_t * ui_playlistsButton1;
lv_obj_t * ui_playlistsImage1;
lv_obj_t * ui_playlistsLabel1;
lv_obj_t * ui_settingsPanel1;
lv_obj_t * ui_settingsButton1;
lv_obj_t * ui_settingsImage1;
lv_obj_t * ui_settingsLabel1;
lv_obj_t * ui_rowPanel;
lv_obj_t * ui_songPanel;
lv_obj_t * ui_songImage;
lv_obj_t * ui_songTitle;
lv_obj_t * ui_contextLabel;
lv_obj_t * ui_lengthLabel;
lv_obj_t * ui_pausePlayButton;

// event funtions

// build funtions

void ui_songScreen_screen_init(void)
{
    ui_songScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_songScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_songScreen, &ui_img_1559207837, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_songScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_songScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_songScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_songScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_songScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_songScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menupanel1 = lv_obj_create(ui_songScreen);
    lv_obj_set_width(ui_menupanel1, 240);
    lv_obj_set_height(ui_menupanel1, 480);
    lv_obj_set_align(ui_menupanel1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_menupanel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_menupanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_menupanel1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_menupanel1, LV_DIR_VER);
    lv_obj_set_style_radius(ui_menupanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_menupanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menupanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_menupanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_menupanel1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_menupanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_menupanel1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_menupanel1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_menupanel1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_menupanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playingPanel1 = lv_obj_create(ui_menupanel1);
    lv_obj_set_width(ui_playingPanel1, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_playingPanel1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_playingPanel1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_playingPanel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_playingPanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_playingPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_playingPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playingPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_playingPanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_playingPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_playingPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_playingPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_playingPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playingsButton1 = lv_button_create(ui_playingPanel1);
    lv_obj_set_width(ui_playingsButton1, 70);
    lv_obj_set_height(ui_playingsButton1, 70);
    lv_obj_set_align(ui_playingsButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playingsButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_playingsButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_playingsButton1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_playingsButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playingsButton1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playingImage1 = lv_image_create(ui_playingsButton1);
    lv_image_set_src(ui_playingImage1, &ui_img_playing_png);
    lv_obj_set_width(ui_playingImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playingImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_playingImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playingImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_playingImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_playingLabel1 = lv_label_create(ui_playingPanel1);
    lv_obj_set_width(ui_playingLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playingLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_playingLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_playingLabel1, "Playing");
    lv_obj_set_style_text_letter_space(ui_playingLabel1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_playingLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_playingLabel1, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homePanel1 = lv_obj_create(ui_menupanel1);
    lv_obj_set_width(ui_homePanel1, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_homePanel1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_homePanel1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_homePanel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_homePanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_homePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homePanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_homePanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_homePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_homePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_homePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_homePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeButton1 = lv_button_create(ui_homePanel1);
    lv_obj_set_width(ui_homeButton1, 70);
    lv_obj_set_height(ui_homeButton1, 70);
    lv_obj_set_align(ui_homeButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homeButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_homeButton1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homeButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeButton1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeImage1 = lv_image_create(ui_homeButton1);
    lv_image_set_src(ui_homeImage1, &ui_img_home_png);
    lv_obj_set_width(ui_homeImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homeImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_homeImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homeImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_homeImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homeLabel1 = lv_label_create(ui_homePanel1);
    lv_obj_set_width(ui_homeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_homeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_homeLabel1, "Home");
    lv_obj_set_style_text_letter_space(ui_homeLabel1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_homeLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_homeLabel1, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_libraryPanel1 = lv_obj_create(ui_menupanel1);
    lv_obj_set_width(ui_libraryPanel1, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_libraryPanel1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_libraryPanel1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_libraryPanel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_libraryPanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_libraryPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_libraryPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_libraryPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_libraryPanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_libraryPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_libraryPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_libraryPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_libraryPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_libraryButton1 = lv_button_create(ui_libraryPanel1);
    lv_obj_set_width(ui_libraryButton1, 70);
    lv_obj_set_height(ui_libraryButton1, 70);
    lv_obj_set_align(ui_libraryButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_libraryButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_libraryButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_libraryButton1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_libraryButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_libraryButton1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_libraryImage1 = lv_image_create(ui_libraryButton1);
    lv_image_set_src(ui_libraryImage1, &ui_img_library_png);
    lv_obj_set_width(ui_libraryImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_libraryImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_libraryImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_libraryImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_libraryImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_libraryLabel1 = lv_label_create(ui_libraryPanel1);
    lv_obj_set_width(ui_libraryLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_libraryLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_libraryLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_libraryLabel1, "Library");
    lv_obj_set_style_text_letter_space(ui_libraryLabel1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_libraryLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_libraryLabel1, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumsPanel1 = lv_obj_create(ui_menupanel1);
    lv_obj_set_width(ui_albumsPanel1, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_albumsPanel1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_albumsPanel1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_albumsPanel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_albumsPanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_albumsPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_albumsPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_albumsPanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_albumsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_albumsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_albumsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_albumsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumsButton1 = lv_button_create(ui_albumsPanel1);
    lv_obj_set_width(ui_albumsButton1, 70);
    lv_obj_set_height(ui_albumsButton1, 70);
    lv_obj_set_align(ui_albumsButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_albumsButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_albumsButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_albumsButton1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_albumsButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_albumsButton1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_albumsImage1 = lv_image_create(ui_albumsButton1);
    lv_image_set_src(ui_albumsImage1, &ui_img_albums_png);
    lv_obj_set_width(ui_albumsImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_albumsImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_albumsImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_albumsImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_albumsImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_albumsLabel1 = lv_label_create(ui_albumsPanel1);
    lv_obj_set_width(ui_albumsLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_albumsLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_albumsLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_albumsLabel1, "Albums");
    lv_obj_set_style_text_letter_space(ui_albumsLabel1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_albumsLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_albumsLabel1, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_artistsPanel1 = lv_obj_create(ui_menupanel1);
    lv_obj_set_width(ui_artistsPanel1, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_artistsPanel1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_artistsPanel1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_artistsPanel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_artistsPanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_artistsPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_artistsPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_artistsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_artistsPanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_artistsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_artistsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_artistsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_artistsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_artistsButton1 = lv_button_create(ui_artistsPanel1);
    lv_obj_set_width(ui_artistsButton1, 70);
    lv_obj_set_height(ui_artistsButton1, 70);
    lv_obj_set_align(ui_artistsButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_artistsButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_artistsButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_artistsButton1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_artistsButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_artistsButton1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_artistsImage1 = lv_image_create(ui_artistsButton1);
    lv_image_set_src(ui_artistsImage1, &ui_img_artist_png);
    lv_obj_set_width(ui_artistsImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_artistsImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_artistsImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_artistsImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_artistsImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_artistsLabel1 = lv_label_create(ui_artistsPanel1);
    lv_obj_set_width(ui_artistsLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_artistsLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_artistsLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_artistsLabel1, "Artists");
    lv_obj_set_style_text_letter_space(ui_artistsLabel1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_artistsLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_artistsLabel1, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playlistsPanel1 = lv_obj_create(ui_menupanel1);
    lv_obj_set_width(ui_playlistsPanel1, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_playlistsPanel1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_playlistsPanel1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_playlistsPanel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_playlistsPanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_playlistsPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_playlistsPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playlistsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_playlistsPanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_playlistsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_playlistsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_playlistsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_playlistsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playlistsButton1 = lv_button_create(ui_playlistsPanel1);
    lv_obj_set_width(ui_playlistsButton1, 70);
    lv_obj_set_height(ui_playlistsButton1, 70);
    lv_obj_set_align(ui_playlistsButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playlistsButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_playlistsButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_playlistsButton1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_playlistsButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playlistsButton1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playlistsImage1 = lv_image_create(ui_playlistsButton1);
    lv_image_set_src(ui_playlistsImage1, &ui_img_playlist_png);
    lv_obj_set_width(ui_playlistsImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playlistsImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_playlistsImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playlistsImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_playlistsImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_playlistsLabel1 = lv_label_create(ui_playlistsPanel1);
    lv_obj_set_width(ui_playlistsLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playlistsLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_playlistsLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_playlistsLabel1, "Playlists");
    lv_obj_set_style_text_letter_space(ui_playlistsLabel1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_playlistsLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_playlistsLabel1, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsPanel1 = lv_obj_create(ui_menupanel1);
    lv_obj_set_width(ui_settingsPanel1, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_settingsPanel1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_settingsPanel1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_settingsPanel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_settingsPanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settingsPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_settingsPanel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_settingsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_settingsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_settingsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_settingsPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsButton1 = lv_button_create(ui_settingsPanel1);
    lv_obj_set_width(ui_settingsButton1, 70);
    lv_obj_set_height(ui_settingsButton1, 70);
    lv_obj_set_align(ui_settingsButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_settingsButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_settingsButton1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settingsButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsButton1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsImage1 = lv_image_create(ui_settingsButton1);
    lv_image_set_src(ui_settingsImage1, &ui_img_settings_png);
    lv_obj_set_width(ui_settingsImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settingsImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsImage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_settingsImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingsLabel1 = lv_label_create(ui_settingsPanel1);
    lv_obj_set_width(ui_settingsLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settingsLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settingsLabel1, "Settings");
    lv_obj_set_style_text_letter_space(ui_settingsLabel1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_settingsLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settingsLabel1, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rowPanel = lv_obj_create(ui_songScreen);
    lv_obj_set_width(ui_rowPanel, 560);
    lv_obj_set_height(ui_rowPanel, 480);
    lv_obj_set_x(ui_rowPanel, 240);
    lv_obj_set_y(ui_rowPanel, 1);
    lv_obj_set_align(ui_rowPanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_rowPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_rowPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_rowPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_rowPanel, LV_DIR_VER);
    lv_obj_set_scroll_snap_y(ui_rowPanel, LV_SCROLL_SNAP_START);
    lv_obj_set_style_radius(ui_rowPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rowPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rowPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rowPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rowPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rowPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rowPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rowPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_rowPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_rowPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_songPanel = lv_obj_create(ui_rowPanel);
    lv_obj_set_width(ui_songPanel, 540);
    lv_obj_set_height(ui_songPanel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_songPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_songPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_songPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_songPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_songPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_songPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_songPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_songPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_songPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_songPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_songImage = lv_image_create(ui_songPanel);
    lv_obj_set_width(ui_songImage, 64);
    lv_obj_set_height(ui_songImage, 64);
    lv_obj_set_align(ui_songImage, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_songImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_songImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_songTitle = lv_label_create(ui_songPanel);
    lv_obj_set_width(ui_songTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_songTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_songTitle, 100);
    lv_obj_set_y(ui_songTitle, -15);
    lv_obj_set_align(ui_songTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_songTitle, "Song Title One");
    lv_obj_set_style_text_font(ui_songTitle, &ui_font_Inter28Medium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contextLabel = lv_label_create(ui_songPanel);
    lv_obj_set_width(ui_contextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_contextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_contextLabel, 100);
    lv_obj_set_y(ui_contextLabel, 20);
    lv_obj_set_align(ui_contextLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_contextLabel, "Artist Name - Album Name");
    lv_obj_set_style_text_font(ui_contextLabel, &ui_font_inter162, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lengthLabel = lv_label_create(ui_songPanel);
    lv_obj_set_width(ui_lengthLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lengthLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lengthLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lengthLabel, "3:45");
    lv_obj_set_style_text_font(ui_lengthLabel, &ui_font_inter162, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pausePlayButton = lv_button_create(ui_songScreen);
    lv_obj_set_width(ui_pausePlayButton, 100);
    lv_obj_set_height(ui_pausePlayButton, 100);
    lv_obj_set_x(ui_pausePlayButton, -20);
    lv_obj_set_y(ui_pausePlayButton, -20);
    lv_obj_set_align(ui_pausePlayButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_pausePlayButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_pausePlayButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pausePlayButton, 75, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pausePlayButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pausePlayButton, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pausePlayButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_pausePlayButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

}

void ui_songScreen_screen_destroy(void)
{
    if(ui_songScreen) lv_obj_del(ui_songScreen);

    // NULL screen variables
    ui_songScreen = NULL;
    ui_menupanel1 = NULL;
    ui_playingPanel1 = NULL;
    ui_playingsButton1 = NULL;
    ui_playingImage1 = NULL;
    ui_playingLabel1 = NULL;
    ui_homePanel1 = NULL;
    ui_homeButton1 = NULL;
    ui_homeImage1 = NULL;
    ui_homeLabel1 = NULL;
    ui_libraryPanel1 = NULL;
    ui_libraryButton1 = NULL;
    ui_libraryImage1 = NULL;
    ui_libraryLabel1 = NULL;
    ui_albumsPanel1 = NULL;
    ui_albumsButton1 = NULL;
    ui_albumsImage1 = NULL;
    ui_albumsLabel1 = NULL;
    ui_artistsPanel1 = NULL;
    ui_artistsButton1 = NULL;
    ui_artistsImage1 = NULL;
    ui_artistsLabel1 = NULL;
    ui_playlistsPanel1 = NULL;
    ui_playlistsButton1 = NULL;
    ui_playlistsImage1 = NULL;
    ui_playlistsLabel1 = NULL;
    ui_settingsPanel1 = NULL;
    ui_settingsButton1 = NULL;
    ui_settingsImage1 = NULL;
    ui_settingsLabel1 = NULL;
    ui_rowPanel = NULL;
    ui_songPanel = NULL;
    ui_songImage = NULL;
    ui_songTitle = NULL;
    ui_contextLabel = NULL;
    ui_lengthLabel = NULL;
    ui_pausePlayButton = NULL;

}
