// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: spotify_api_v2

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_menupanel;
extern lv_obj_t * ui_nowPlayingPanel;
extern void ui_event_nowPlayingButton(lv_event_t * e);
extern lv_obj_t * ui_nowPlayingButton;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_nowPlayingLabel;
extern lv_obj_t * ui_nowPlayingPanel1;
extern lv_obj_t * ui_nowPlayingButton1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_nowPlayingLabel1;
extern lv_obj_t * ui_nowPlayingPanel2;
extern lv_obj_t * ui_nowPlayingButton2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_nowPlayingLabel2;
extern lv_obj_t * ui_nowPlayingPanel3;
extern lv_obj_t * ui_nowPlayingButton3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_nowPlayingLabel3;
extern lv_obj_t * ui_nowPlayingPanel4;
extern lv_obj_t * ui_nowPlayingButton4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_nowPlayingLabel4;
extern lv_obj_t * ui_nowPlayingPanel5;
extern lv_obj_t * ui_nowPlayingButton5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_nowPlayingLabel5;
extern lv_obj_t * ui_contentpanel;
extern lv_obj_t * ui_contentItemPanel;
extern lv_obj_t * ui_albumCoverButton;
extern lv_obj_t * ui_contentTitle;
extern lv_obj_t * ui_creatorLabel;
extern lv_obj_t * ui_contentItemPanel10;
extern lv_obj_t * ui_albumCoverButton10;
extern lv_obj_t * ui_contentTitle10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

